{{- if .Values.upbound.controlPlane.connect }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "agent-name" . }}-graphql
  labels:
    {{- include "labelsGraphql" . | nindent 4 }}
{{- end }}