{{- if .Values.upbound.controlPlane.connect }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "agent-name" . }}
  labels:
    {{- include "labelsAgent" . | nindent 4 }}
spec:
  selector:
    {{- include "selectorLabelsAgent" . | nindent 4 }}
  ports:
    - port: 6443
      targetPort: 6443
      protocol: TCP
      name: https
---
# legacy service - drop once router uses new one
apiVersion: v1
kind: Service
metadata:
  name: tenant-gateway
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  selector:
    {{- include "selectorLabelsAgent" . | nindent 4 }}
  ports:
    - port: 6443
      targetPort: 6443
      protocol: TCP
      name: https
{{- end }}