{{- if .Values.upbound.controlPlane.connect }}
apiVersion: v1
kind: Secret
metadata:
  name: crossplane-graphql-tls
  labels:
    {{- include "labelsGraphql" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: kubernetes.io/tls
data:
  ca.crt: ""
  tls.crt: ""
  tls.key: ""
{{- end }}