{{- if or (eq .Values.upbound.controlPlane.permission "view") (eq .Values.upbound.controlPlane.permission "edit") }}
apiVersion: v1
kind: Secret
metadata:
  name: upbound-agent-ca
  labels:
    {{- include "labels" . | nindent 4 }}
type: Opaque
{{- end }}