{{- if .Values.upbound.controlPlane.connect }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "name" . }}-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "name" . }}-admin
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: upbound:admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "name" . }}-edit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "name" . }}-edit
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: upbound:edit
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "name" . }}-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "name" . }}-view
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: upbound:view
{{- end }}