{{- if .Values.upbound.controlPlane.connect }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "agent-name" . }}
  labels:
    {{- include "labelsAgent" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    resourceNames: ["kube-system"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "agent-name" . }}-impersonator
  labels:
    {{- include "labelsAgent" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["users"]
    verbs: ["impersonate"]
    resourceNames: ["upbound-cloud-user"]
  - apiGroups: ["authentication.k8s.io"]
    resources: ["userextras/user-on-upbound-cloud"]
    verbs: ["impersonate"]
  - apiGroups: [""]
    resources: ["groups"]
    verbs: ["impersonate"]
{{- end }}