{{- if or (eq .Values.upbound.controlPlane.permission "View") (eq .Values.upbound.controlPlane.permission "Edit") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "agent-name" . }}
  labels:
    {{- include "labelsAgent" . | nindent 4 }}
{{- end }}