{{- if or (eq .Values.upbound.controlPlane.permission "View") (eq .Values.upbound.controlPlane.permission "Edit") }}
apiVersion: v1
kind: Secret
metadata:
  name: upbound-agent-tls
  labels:
    {{- include "labelsAgent" . | nindent 4 }}
{{- end }}