{{- if .Values.upbound.controlPlane.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "name" . }}-connect
  labels:
    {{- include "labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "-1"
data:
  {{- (.Files.Glob "files/connect.sh").AsConfig | nindent 2 }}
{{- end }}