{{- if .Values.upbound.controlPlane.create }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "name" . }}-connect
  labels:
    {{- include "labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  template:
    spec:
      serviceAccountName: {{ template "name" . }}-connect
      containers:
        - name: connect
          image: turkenh/kubedebug:0.2.4
          command:
            - /scripts/connect.sh
          env:
            - name: CONTROL_PLANE_NAME
              value: {{ .Values.upbound.controlPlane.name }}
            - name: CONTROL_PLANE_ORG
              value: {{ .Values.upbound.controlPlane.organization }}
            - name: UPBOUND_CROSSPLANE_NAMESPACE
              value: {{ .Release.Namespace }}
            - name: UPBOUND_API_ENDPOINT
              value: {{ .Values.upbound.apiEndpoint }}
            - name: UPBOUND_PLATFORM_TOKEN_SECRET_NAME
              value: {{ .Values.gateway.config.platformTokenSecret }}
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ template "name" . }}-connect-apitoken
                  key: token
          volumeMounts:
            - name: connect-script
              mountPath: /scripts/connect.sh
              subPath: connect.sh
      volumes:
        - name: connect-script
          configMap:
            name: {{ template "name" . }}-connect
            defaultMode: 0777
      restartPolicy: Never
  backoffLimit: 3
{{- end}}