apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "name" . }}-graphql
  labels:
    {{- include "labelsGraphql" . | nindent 4 }}
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - list
      - watch
      - get
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
      - clusterrolebindings
      - roles
      - rolebindings
    verbs:
      - list
      - watch
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crossplane-graphql:aggregate-to-browse
  labels:
    {{- include "labelsGraphql" . | nindent 4 }}
    rbac.crossplane.io/aggregate-to-browse: "true"
rules:
- apiGroups: [""]
  resources: [namespaces]
  verbs: [get, list, watch]
# Why does the frontend need this?
- apiGroups: ["pkg.crossplane.io"]
  resources: [configurations,providers]
  verbs: [get, list, watch]
