apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: crossplane
    chart: universal-crossplane-0.0.1
    heritage: Helm
    rbac.crossplane.io/aggregate-to-admin: "true"
    release: universal-crossplane
  name: crossplane:aggregate-to-admin
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  - namespaces
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - roles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - rolebindings
  verbs:
  - '*'
- apiGroups:
  - apiextensions.crossplane.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - pkg.crossplane.io
  resources:
  - providers
  - configurations
  - providerrevisions
  - configurationrevisions
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
