apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: crossplane
    chart: upbound-universal-crossplane-0.0.1
    heritage: Helm
    rbac.crossplane.io/aggregate-to-edit: "true"
    release: crossplane-distro
  name: crossplane:aggregate-to-edit
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apiextensions.crossplane.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - pkg.crossplane.io
  resources:
  - providers
  - configurations
  - providerrevisions
  - configurationrevisions
  verbs:
  - '*'
