apiVersion: v1
data:
  ca.crt: ""
  tls.crt: ""
  tls.key: ""
kind: Secret
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation
  labels:
    app.kubernetes.io/component: graphql
    app.kubernetes.io/instance: crossplane-distro
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: crossplane
    app.kubernetes.io/version: 0.0.1
    helm.sh/chart: upbound-universal-crossplane-0.0.1
  name: crossplane-graphql-tls
type: kubernetes.io/tls
