apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: agent
    app.kubernetes.io/instance: universal-crossplane
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: crossplane
    app.kubernetes.io/version: 0.0.1
    helm.sh/chart: upbound-universal-crossplane-0.0.1
  name: upbound-agent-impersonator
rules:
- apiGroups:
  - ""
  resources:
  - users
  verbs:
  - impersonate
- apiGroups:
  - ""
  resources:
  - groups
  verbs:
  - impersonate
