apiVersion: v1
imagePullSecrets:
- name: dockerhub
kind: ServiceAccount
metadata:
  labels:
    app: crossplane
    chart: upbound-universal-crossplane-0.0.1
    heritage: Helm
    release: crossplane-distro
  name: crossplane
