apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: graphql
    app.kubernetes.io/instance: crossplane-distro
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: crossplane
    app.kubernetes.io/version: 0.0.1
    helm.sh/chart: upbound-universal-crossplane-0.0.1
  name: crossplane-graphql
