aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.crossplane.io/aggregate-to-allowed-provider-permissions: "true"
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: crossplane
    chart: upbound-universal-crossplane-0.0.1
    heritage: Helm
    release: crossplane-distro
  name: crossplane:allowed-provider-permissions
