apiVersion: v1
kind: Secret
metadata:
  name: xgql-tls
  labels:
    {{- include "labelsXgql" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: kubernetes.io/tls
data:
  ca.crt: ""
  tls.crt: ""
  tls.key: ""
